### ISSUE TITLE
developping locally

### ISSUE THREAD

**Issue by pmavros** [o-p-e-n-s-e-t/flocc#83]
Hi Scott, 

thanks for the awesome package. 
I am not very experienced with js in case this is obvious:

I have tweaked the example in the code sandbox, but now i want to develop locally to merge with the rest of my script. In the readme, you write "you can download the top-level flocc.js file and...". i have downloaded the latest release and I cannot locate the said file. I have placed the entire folder in the my src folder, but it does not work – is it the CORS blocking it?

Thanks, 
Panos

**Comment by scottpdo** [comment]
Hi @pmavros thanks for the kind words! Rather than downloading the release from GitHub (if that's what you did), I would recommend getting the latest version from Unpkg here: https://unpkg.com/flocc (either save that as a JS file or copy and paste the code). If you do that, you can include it wherever you like. Let me know if that helps.

**Comment by pmavros** [comment]
Thanks Scott that helps a lot!
